# Custom Models and Training with TensorFlow

Up until now we've used only TensorFlow high-level API, `tf.keras`. In most cases you will only use `tf.keras`. But when you want want extra control over your model, cost function, optimization, etc then you have to know about TensorFlow's low-level API.

# A Quick tour of TensorFlow

TensorFlow is the most popular Machine Learning framework.

- Its core is similar to NumPy but with GPU.
- It supports distributed computing.
- It uses computational graphs which can be exported in any format. (with this you can use it with python or javascript)

TensorFlow offers many features such as preprocessing, model building, visualization, deployment, mathematics, etc.

TensorFlow's Python API overview:

```python
# High-level
tf.keras
tf.estimators

# Low-level
tf.nn
tf.losses
tf.metrices
tf.optimizers
tf.train
tf.initializers

# Autodiff
tf.GradientTape
tf.gradients()

# I/O and prerpcessing
tf.data
tf.image
tf.audio
tf.feature_column
tf.io
tf.queue
```

# Using TensorFlow like NumPy

TensorFlow uses *tensors*, which flow from operation to operation hence the name TensorFlow. A tensor is basically a multi-dimensional array. 

## Tensors and Operations

Creating tensor:

In [4]:
import tensorflow as tf

t = tf.constant([[1., 2., 3.], [4., 5., 6.]]) # matrix
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [3]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

Shape and type:

In [5]:
t.shape

TensorShape([2, 3])

In [6]:
t.dtype

tf.float32

Slicing like NumPy array:

In [7]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [10]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

Operations

In [11]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [12]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [13]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

## Tensors and NumPy

Tensors are friendly to NumPy arrays, they can be converted into each other:

In [14]:
import numpy as np

a = np.array([2., 4., 6.])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 6.])>

In [15]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

You can even apply TensorFlow operations to NumPy array and vice-versa:

In [16]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 36.])>

In [17]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

> Type conversion is sensitive in TensorFlow so be careful when using different types.

## Variables

The `tf.Tensor` are immutable, you can't modify them. So, for weights we need `tf.Variable`:

In [18]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

They are pretty much same as `tf.Tensor`. Now, you can modify them using `assign()` method:

In [21]:
print(v.assign(2 * v))
print(v[0, 1].assign(42))
print(v[:, 2].assign([0., 1.]))
print(v.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[100., 200.]))

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 8., 84.,  0.],
       [32., 40.,  2.]], dtype=float32)>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 8., 42.,  0.],
       [32., 40.,  2.]], dtype=float32)>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 8., 42.,  0.],
       [32., 40.,  1.]], dtype=float32)>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [ 32.,  40., 200.]], dtype=float32)>
